// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.12.0
// source: membershipservice_definition.proto

package fs533pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type JoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeAddress   string `protobuf:"bytes,1,opt,name=nodeAddress,proto3" json:"nodeAddress,omitempty"`
	NodeName      string `protobuf:"bytes,2,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	NeedSpreading bool   `protobuf:"varint,3,opt,name=needSpreading,proto3" json:"needSpreading,omitempty"`
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membershipservice_definition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membershipservice_definition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_membershipservice_definition_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *JoinRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *JoinRequest) GetNeedSpreading() bool {
	if x != nil {
		return x.NeedSpreading
	}
	return false
}

type JoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members                  []string                          `protobuf:"bytes,1,rep,name=Members,proto3" json:"Members,omitempty"`
	MasterNode               string                            `protobuf:"bytes,2,opt,name=MasterNode,proto3" json:"MasterNode,omitempty"`
	ElectionTerm             int32                             `protobuf:"varint,3,opt,name=ElectionTerm,proto3" json:"ElectionTerm,omitempty"`
	Fs533Files               []*JoinResponse_Fs533FileMetadata `protobuf:"bytes,4,rep,name=Fs533Files,proto3" json:"Fs533Files,omitempty"`
	PendingWriteTransactions []*JoinResponse_WriteTransaction  `protobuf:"bytes,5,rep,name=PendingWriteTransactions,proto3" json:"PendingWriteTransactions,omitempty"`
	JoinStatus               bool                              `protobuf:"varint,6,opt,name=JoinStatus,proto3" json:"JoinStatus,omitempty"`
	ErrorMessage             string                            `protobuf:"bytes,7,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membershipservice_definition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membershipservice_definition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_membershipservice_definition_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *JoinResponse) GetMasterNode() string {
	if x != nil {
		return x.MasterNode
	}
	return ""
}

func (x *JoinResponse) GetElectionTerm() int32 {
	if x != nil {
		return x.ElectionTerm
	}
	return 0
}

func (x *JoinResponse) GetFs533Files() []*JoinResponse_Fs533FileMetadata {
	if x != nil {
		return x.Fs533Files
	}
	return nil
}

func (x *JoinResponse) GetPendingWriteTransactions() []*JoinResponse_WriteTransaction {
	if x != nil {
		return x.PendingWriteTransactions
	}
	return nil
}

func (x *JoinResponse) GetJoinStatus() bool {
	if x != nil {
		return x.JoinStatus
	}
	return false
}

func (x *JoinResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type LeaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeavingNodeAddress   string `protobuf:"bytes,1,opt,name=leavingNodeAddress,proto3" json:"leavingNodeAddress,omitempty"`
	RequesterNodeAddress string `protobuf:"bytes,2,opt,name=requesterNodeAddress,proto3" json:"requesterNodeAddress,omitempty"`
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membershipservice_definition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membershipservice_definition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_membershipservice_definition_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveRequest) GetLeavingNodeAddress() string {
	if x != nil {
		return x.LeavingNodeAddress
	}
	return ""
}

func (x *LeaveRequest) GetRequesterNodeAddress() string {
	if x != nil {
		return x.RequesterNodeAddress
	}
	return ""
}

type LeaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaveStatus  bool   `protobuf:"varint,1,opt,name=leaveStatus,proto3" json:"leaveStatus,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membershipservice_definition_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membershipservice_definition_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_membershipservice_definition_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveResponse) GetLeaveStatus() bool {
	if x != nil {
		return x.LeaveStatus
	}
	return false
}

func (x *LeaveResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type JoinResponse_WriteTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fs533FileName    string   `protobuf:"bytes,1,opt,name=Fs533FileName,proto3" json:"Fs533FileName,omitempty"`
	Fs533FileVersion int32    `protobuf:"varint,2,opt,name=Fs533FileVersion,proto3" json:"Fs533FileVersion,omitempty"`
	RequestID        string   `protobuf:"bytes,3,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	PreferenceNodes  []string `protobuf:"bytes,4,rep,name=PreferenceNodes,proto3" json:"PreferenceNodes,omitempty"`
	RegisteredTime   int64    `protobuf:"varint,5,opt,name=RegisteredTime,proto3" json:"RegisteredTime,omitempty"`
}

func (x *JoinResponse_WriteTransaction) Reset() {
	*x = JoinResponse_WriteTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membershipservice_definition_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse_WriteTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse_WriteTransaction) ProtoMessage() {}

func (x *JoinResponse_WriteTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_membershipservice_definition_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse_WriteTransaction.ProtoReflect.Descriptor instead.
func (*JoinResponse_WriteTransaction) Descriptor() ([]byte, []int) {
	return file_membershipservice_definition_proto_rawDescGZIP(), []int{1, 0}
}

func (x *JoinResponse_WriteTransaction) GetFs533FileName() string {
	if x != nil {
		return x.Fs533FileName
	}
	return ""
}

func (x *JoinResponse_WriteTransaction) GetFs533FileVersion() int32 {
	if x != nil {
		return x.Fs533FileVersion
	}
	return 0
}

func (x *JoinResponse_WriteTransaction) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *JoinResponse_WriteTransaction) GetPreferenceNodes() []string {
	if x != nil {
		return x.PreferenceNodes
	}
	return nil
}

func (x *JoinResponse_WriteTransaction) GetRegisteredTime() int64 {
	if x != nil {
		return x.RegisteredTime
	}
	return 0
}

type JoinResponse_Fs533FileMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fs533FileName    string   `protobuf:"bytes,1,opt,name=Fs533FileName,proto3" json:"Fs533FileName,omitempty"`
	Fs533FileVersion int32    `protobuf:"varint,2,opt,name=Fs533FileVersion,proto3" json:"Fs533FileVersion,omitempty"`
	Fs533FileSize    int32    `protobuf:"varint,3,opt,name=Fs533FileSize,proto3" json:"Fs533FileSize,omitempty"`
	PreferenceNodes  []string `protobuf:"bytes,4,rep,name=PreferenceNodes,proto3" json:"PreferenceNodes,omitempty"`
}

func (x *JoinResponse_Fs533FileMetadata) Reset() {
	*x = JoinResponse_Fs533FileMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membershipservice_definition_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse_Fs533FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse_Fs533FileMetadata) ProtoMessage() {}

func (x *JoinResponse_Fs533FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_membershipservice_definition_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse_Fs533FileMetadata.ProtoReflect.Descriptor instead.
func (*JoinResponse_Fs533FileMetadata) Descriptor() ([]byte, []int) {
	return file_membershipservice_definition_proto_rawDescGZIP(), []int{1, 1}
}

func (x *JoinResponse_Fs533FileMetadata) GetFs533FileName() string {
	if x != nil {
		return x.Fs533FileName
	}
	return ""
}

func (x *JoinResponse_Fs533FileMetadata) GetFs533FileVersion() int32 {
	if x != nil {
		return x.Fs533FileVersion
	}
	return 0
}

func (x *JoinResponse_Fs533FileMetadata) GetFs533FileSize() int32 {
	if x != nil {
		return x.Fs533FileSize
	}
	return 0
}

func (x *JoinResponse_Fs533FileMetadata) GetPreferenceNodes() []string {
	if x != nil {
		return x.PreferenceNodes
	}
	return nil
}

var File_membershipservice_definition_proto protoreflect.FileDescriptor

var file_membershipservice_definition_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x73, 0x35, 0x33, 0x33, 0x70, 0x62, 0x22, 0x71, 0x0a,
	0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x65,
	0x65, 0x64, 0x53, 0x70, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0d, 0x6e, 0x65, 0x65, 0x64, 0x53, 0x70, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67,
	0x22, 0xec, 0x05, 0x0a, 0x0c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x45,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x72, 0x6d, 0x12,
	0x47, 0x0a, 0x0a, 0x46, 0x73, 0x35, 0x33, 0x33, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x66, 0x73, 0x35, 0x33, 0x33, 0x70, 0x62, 0x2e, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x73, 0x35, 0x33, 0x33,
	0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x46, 0x73,
	0x35, 0x33, 0x33, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x62, 0x0a, 0x18, 0x50, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x66, 0x73, 0x35,
	0x33, 0x33, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x18, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0xd4, 0x01, 0x0a, 0x10, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x46, 0x73, 0x35, 0x33, 0x33, 0x46, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x46, 0x73,
	0x35, 0x33, 0x33, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x46,
	0x73, 0x35, 0x33, 0x33, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x46, 0x73, 0x35, 0x33, 0x33, 0x46, 0x69, 0x6c, 0x65,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f,
	0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12,
	0x26, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0xb5, 0x01, 0x0a, 0x11, 0x46, 0x73, 0x35, 0x33,
	0x33, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x24, 0x0a,
	0x0d, 0x46, 0x73, 0x35, 0x33, 0x33, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x46, 0x73, 0x35, 0x33, 0x33, 0x46, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x46, 0x73, 0x35, 0x33, 0x33, 0x46, 0x69, 0x6c, 0x65,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x46,
	0x73, 0x35, 0x33, 0x33, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x24, 0x0a, 0x0d, 0x46, 0x73, 0x35, 0x33, 0x33, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x46, 0x73, 0x35, 0x33, 0x33, 0x46, 0x69, 0x6c,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f,
	0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22,
	0x72, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2e, 0x0a, 0x12, 0x6c, 0x65, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x6c, 0x65, 0x61,
	0x76, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x32, 0x0a, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x55, 0x0a, 0x0d, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6c, 0x65, 0x61, 0x76, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x80, 0x01, 0x0a, 0x11, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x68, 0x69, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x33, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x14, 0x2e, 0x66, 0x73, 0x35, 0x33, 0x33,
	0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x66, 0x73, 0x35, 0x33, 0x33, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12, 0x15,
	0x2e, 0x66, 0x73, 0x35, 0x33, 0x33, 0x70, 0x62, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x66, 0x73, 0x35, 0x33, 0x33, 0x70, 0x62, 0x2e,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x3b, 0x66, 0x73, 0x35, 0x33, 0x33, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_membershipservice_definition_proto_rawDescOnce sync.Once
	file_membershipservice_definition_proto_rawDescData = file_membershipservice_definition_proto_rawDesc
)

func file_membershipservice_definition_proto_rawDescGZIP() []byte {
	file_membershipservice_definition_proto_rawDescOnce.Do(func() {
		file_membershipservice_definition_proto_rawDescData = protoimpl.X.CompressGZIP(file_membershipservice_definition_proto_rawDescData)
	})
	return file_membershipservice_definition_proto_rawDescData
}

var file_membershipservice_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_membershipservice_definition_proto_goTypes = []interface{}{
	(*JoinRequest)(nil),                    // 0: fs533pb.JoinRequest
	(*JoinResponse)(nil),                   // 1: fs533pb.JoinResponse
	(*LeaveRequest)(nil),                   // 2: fs533pb.LeaveRequest
	(*LeaveResponse)(nil),                  // 3: fs533pb.LeaveResponse
	(*JoinResponse_WriteTransaction)(nil),  // 4: fs533pb.JoinResponse.WriteTransaction
	(*JoinResponse_Fs533FileMetadata)(nil), // 5: fs533pb.JoinResponse.Fs533FileMetadata
}
var file_membershipservice_definition_proto_depIdxs = []int32{
	5, // 0: fs533pb.JoinResponse.Fs533Files:type_name -> fs533pb.JoinResponse.Fs533FileMetadata
	4, // 1: fs533pb.JoinResponse.PendingWriteTransactions:type_name -> fs533pb.JoinResponse.WriteTransaction
	0, // 2: fs533pb.MemberShipService.Join:input_type -> fs533pb.JoinRequest
	2, // 3: fs533pb.MemberShipService.Leave:input_type -> fs533pb.LeaveRequest
	1, // 4: fs533pb.MemberShipService.Join:output_type -> fs533pb.JoinResponse
	3, // 5: fs533pb.MemberShipService.Leave:output_type -> fs533pb.LeaveResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_membershipservice_definition_proto_init() }
func file_membershipservice_definition_proto_init() {
	if File_membershipservice_definition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_membershipservice_definition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membershipservice_definition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membershipservice_definition_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membershipservice_definition_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membershipservice_definition_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse_WriteTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membershipservice_definition_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse_Fs533FileMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_membershipservice_definition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_membershipservice_definition_proto_goTypes,
		DependencyIndexes: file_membershipservice_definition_proto_depIdxs,
		MessageInfos:      file_membershipservice_definition_proto_msgTypes,
	}.Build()
	File_membershipservice_definition_proto = out.File
	file_membershipservice_definition_proto_rawDesc = nil
	file_membershipservice_definition_proto_goTypes = nil
	file_membershipservice_definition_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MemberShipServiceClient is the client API for MemberShipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MemberShipServiceClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error)
}

type memberShipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemberShipServiceClient(cc grpc.ClientConnInterface) MemberShipServiceClient {
	return &memberShipServiceClient{cc}
}

func (c *memberShipServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, "/fs533pb.MemberShipService/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberShipServiceClient) Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error) {
	out := new(LeaveResponse)
	err := c.cc.Invoke(ctx, "/fs533pb.MemberShipService/Leave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberShipServiceServer is the server API for MemberShipService service.
type MemberShipServiceServer interface {
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	Leave(context.Context, *LeaveRequest) (*LeaveResponse, error)
}

// UnimplementedMemberShipServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMemberShipServiceServer struct {
}

func (*UnimplementedMemberShipServiceServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedMemberShipServiceServer) Leave(context.Context, *LeaveRequest) (*LeaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}

func RegisterMemberShipServiceServer(s *grpc.Server, srv MemberShipServiceServer) {
	s.RegisterService(&_MemberShipService_serviceDesc, srv)
}

func _MemberShipService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberShipServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs533pb.MemberShipService/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberShipServiceServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberShipService_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberShipServiceServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs533pb.MemberShipService/Leave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberShipServiceServer).Leave(ctx, req.(*LeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MemberShipService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs533pb.MemberShipService",
	HandlerType: (*MemberShipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _MemberShipService_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _MemberShipService_Leave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "membershipservice_definition.proto",
}
